{
  "description": "urllib in Python 2.x through 2.7.16 supports the local_file: scheme, which makes it easier for remote attackers to bypass protection mechanisms that blacklist file: URIs, as demonstrated by triggering a urllib.urlopen('local_file:///etc/passwd') call.",
  "releases": {
    "bullseye": {
      "fixed_version": "2.7.16-2",
      "repositories": {
        "bullseye": "2.7.16-3"
      },
      "status": "resolved",
      "urgency": "medium**"
    },
    "buster": {
      "fixed_version": "2.7.16-2",
      "repositories": {
        "buster": "2.7.16-2"
      },
      "status": "resolved",
      "urgency": "medium**"
    },
    "jessie": {
      "fixed_version": "2.7.9-2+deb8u3",
      "repositories": {
        "jessie": "2.7.9-2+deb8u1",
        "jessie-security": "2.7.9-2+deb8u4"
      },
      "status": "resolved",
      "urgency": "medium**"
    },
    "sid": {
      "fixed_version": "2.7.16-2",
      "repositories": {
        "sid": "2.7.16-3"
      },
      "status": "resolved",
      "urgency": "medium**"
    },
    "stretch": {
      "nodsa": "Minor issue",
      "nodsa_reason": "",
      "repositories": {
        "stretch": "2.7.13-2+deb9u3",
        "stretch-security": "2.7.13-2+deb9u3"
      },
      "status": "open",
      "urgency": "medium**"
    }
  },
  "scope": "remote"
}