{
  "description": "The ftp_QUIT function in ftpserver.py in pyftpdlib before 0.5.0 allows remote authenticated users to cause a denial of service (file descriptor exhaustion and daemon outage) by sending a QUIT command during a disallowed data-transfer attempt.",
  "releases": {
    "bullseye": {
      "fixed_version": "0",
      "repositories": {
        "bullseye": "1.5.4-1"
      },
      "status": "resolved",
      "urgency": "unimportant"
    },
    "buster": {
      "fixed_version": "0",
      "repositories": {
        "buster": "1.5.4-1"
      },
      "status": "resolved",
      "urgency": "unimportant"
    },
    "jessie": {
      "fixed_version": "0",
      "repositories": {
        "jessie": "1.2.0-1"
      },
      "status": "resolved",
      "urgency": "unimportant"
    },
    "sid": {
      "fixed_version": "0",
      "repositories": {
        "sid": "1.5.4-1"
      },
      "status": "resolved",
      "urgency": "unimportant"
    },
    "stretch": {
      "fixed_version": "0",
      "repositories": {
        "stretch": "1.5.1-4"
      },
      "status": "resolved",
      "urgency": "unimportant"
    }
  },
  "scope": "remote"
}