{
  "affected_release": [
    {
      "advisory": "RHSA-2019:2030",
      "cpe": "cpe:/o:redhat:enterprise_linux:7",
      "package": "python-2.7.5-86.el7",
      "product_name": "Red Hat Enterprise Linux 7",
      "release_date": "2019-08-06T00:00:00"
    },
    {
      "advisory": "RHSA-2019:1700",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3::el6",
      "package": "python27-python-2.7.16-6.el6",
      "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux 6",
      "release_date": "2019-07-08T00:00:00"
    },
    {
      "advisory": "RHSA-2019:1700",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3::el7",
      "package": "python27-python-2.7.16-6.el7",
      "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux 7",
      "release_date": "2019-07-08T00:00:00"
    }
  ],
  "bugzilla": {
    "description": "\nCVE-2019-9948 python: Undocumented local_file protocol allows remote attackers to bypass protection mechanisms\n    ",
    "id": "1695570",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1695570"
  },
  "cvss3": {
    "cvss3_base_score": "7.4",
    "cvss3_scoring_vector": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:N",
    "status": "verified"
  },
  "cwe": "CWE-749",
  "details": [
    "\nurllib in Python 2.x through 2.7.16 supports the local_file: scheme, which makes it easier for remote attackers to bypass protection mechanisms that blacklist file: URIs, as demonstrated by triggering a urllib.urlopen('local_file:///etc/passwd') call.\n    "
  ],
  "mitigation": "\nIf your application uses a blacklist to prevent \"file://\" schema from being used, consider using a whitelist approach to just allow the schemas you want or add \"local_file://\" schema to your blacklist.\n    ",
  "name": "CVE-2019-9948",
  "package_state": [
    {
      "cpe": "cpe:/a:redhat:rhel_software_collections:3",
      "fix_state": "Affected",
      "package_name": "rh-python36-python",
      "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux"
    },
    {
      "cpe": "cpe:/a:redhat:rhel_software_collections:3",
      "fix_state": "Will not fix",
      "package_name": "rh-python35-python",
      "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux"
    },
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:5",
      "fix_state": "Will not fix",
      "package_name": "python",
      "product_name": "Red Hat Enterprise Linux 5"
    },
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:6",
      "fix_state": "Will not fix",
      "package_name": "python",
      "product_name": "Red Hat Enterprise Linux 6"
    },
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:7",
      "fix_state": "Not affected",
      "package_name": "python3",
      "product_name": "Red Hat Enterprise Linux 7"
    },
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:8",
      "fix_state": "Affected",
      "package_name": "python27:2.7/python2",
      "product_name": "Red Hat Enterprise Linux 8"
    },
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:8",
      "fix_state": "Affected",
      "package_name": "python3",
      "product_name": "Red Hat Enterprise Linux 8"
    },
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:8",
      "fix_state": "Not affected",
      "package_name": "python36:3.6/python36",
      "product_name": "Red Hat Enterprise Linux 8"
    }
  ],
  "public_date": "2019-03-23T00:00:00",
  "statement": "\nRed Hat Enterprise Linux 5: \nThis vulnerability has been rated as having a security impact of Moderate. After evaluation and in accordance with the criteria noted in the product support life cycle, there are no plans to address this issue in an upcoming release. Please contact Red Hat Support for further information.\n\nRed Hat Enterprise Linux 6: \nThis vulnerability has been rated as having a security impact of Moderate. After evaluation and in accordance with the criteria noted in the product support life cycle, there are no plans to address this issue in an upcoming release. Please contact Red Hat Support for further information.\n\nRed Hat Enterprise Linux 8: \nThis vulnerability is currently targeted to be addressed in an upcoming release.\n\nRed Hat Software Collections for Red Hat Enterprise Linux (rh-python35-python):\nThis vulnerability has been rated as having a security impact of Moderate. After evaluation and in accordance with the criteria noted in the product support life cycle, there are no plans to address this issue in an upcoming release. Please contact Red Hat Support for further information.\n\nRed Hat Software Collections for Red Hat Enterprise Linux (rh-python36-python):\nThis vulnerability is currently targeted to be addressed in an upcoming release.\n    ",
  "threat_severity": "Moderate"
}