{
  "bugzilla": {
    "description": "\nCVE-2019-6690 python-gnupg: improper input validation in gnupg.GPG.encrypt() and gnupg.GPG.decrypt()\n    ",
    "id": "1670364",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1670364"
  },
  "cvss3": {
    "cvss3_base_score": "7.5",
    "cvss3_scoring_vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
    "status": "draft"
  },
  "cwe": "CWE-20",
  "details": [
    "\npython-gnupg 0.4.3 allows context-dependent attackers to trick gnupg to decrypt other ciphertext than intended. To perform the attack, the passphrase to gnupg must be controlled by the adversary and the ciphertext should be trusted. Related to a \"CWE-20: Improper Input Validation\" issue affecting the affect functionality component.\n    "
  ],
  "mitigation": "\nFilter out newlines from passphrases before passing them to python-gnupg.\n    ",
  "name": "CVE-2019-6690",
  "package_state": {
    "cpe": "cpe:/a:redhat:network_satellite:6",
    "fix_state": "Not affected",
    "package_name": "python-gnupg",
    "product_name": "Red Hat Satellite 6"
  },
  "public_date": "2019-01-23T00:00:00",
  "statement": "\nThe issue affects the versions of python-gnupg shipped with Red Hat Update Infrastructure 3, however the vulnerable functions are never used by the product.\n\nThe issue affects the versions of python-gnupg shipped with Red Hat Satellite 6, however the vulnerable functions are never used by the product.\n    ",
  "threat_severity": "Moderate",
  "upstream_fix": "python-gnupg 0.4.4"
}