{
  "debianbug": 875960,
  "description": "libarchive 3.3.2 suffers from an out-of-bounds read within lha_read_data_none() in archive_read_support_format_lha.c when extracting a specially crafted lha archive, related to lha_crc16.",
  "releases": {
    "bullseye": {
      "fixed_version": "3.2.2-4.1",
      "repositories": {
        "bullseye": "3.3.3-4"
      },
      "status": "resolved",
      "urgency": "medium**"
    },
    "buster": {
      "fixed_version": "3.2.2-4.1",
      "repositories": {
        "buster": "3.3.3-4"
      },
      "status": "resolved",
      "urgency": "medium**"
    },
    "jessie": {
      "fixed_version": "3.1.2-11+deb8u4",
      "repositories": {
        "jessie": "3.1.2-11+deb8u3",
        "jessie-security": "3.1.2-11+deb8u7"
      },
      "status": "resolved",
      "urgency": "medium**"
    },
    "sid": {
      "fixed_version": "3.2.2-4.1",
      "repositories": {
        "sid": "3.3.3-4"
      },
      "status": "resolved",
      "urgency": "medium**"
    },
    "stretch": {
      "fixed_version": "3.2.2-2+deb9u1",
      "repositories": {
        "stretch": "3.2.2-2+deb9u1",
        "stretch-security": "3.2.2-2+deb9u1"
      },
      "status": "resolved",
      "urgency": "medium**"
    }
  },
  "scope": "remote"
}