{
  "debianbug": 641405,
  "description": "The verify_exists functionality in the URLField implementation in Django before 1.2.7 and 1.3.x before 1.3.1 originally tests a URL's validity through a HEAD request, but then uses a GET request for the new target URL in the case of a redirect, which might allow remote attackers to trigger arbitrary GET requests with an unintended source IP address via a crafted Location header.",
  "releases": {
    "bullseye": {
      "fixed_version": "1.3.1-1",
      "repositories": {
        "bullseye": "1:1.11.23-1~deb10u1"
      },
      "status": "resolved",
      "urgency": "medium**"
    },
    "buster": {
      "fixed_version": "1.3.1-1",
      "repositories": {
        "buster": "1:1.11.21-1",
        "buster-security": "1:1.11.23-1~deb10u1"
      },
      "status": "resolved",
      "urgency": "medium**"
    },
    "jessie": {
      "fixed_version": "1.3.1-1",
      "repositories": {
        "jessie": "1.7.11-1+deb8u3",
        "jessie-security": "1.7.11-1+deb8u7"
      },
      "status": "resolved",
      "urgency": "medium**"
    },
    "sid": {
      "fixed_version": "1.3.1-1",
      "repositories": {
        "sid": "2:2.2.4-1"
      },
      "status": "resolved",
      "urgency": "medium**"
    },
    "stretch": {
      "fixed_version": "1.3.1-1",
      "repositories": {
        "stretch": "1:1.10.7-2+deb9u4",
        "stretch-security": "1:1.10.7-2+deb9u6"
      },
      "status": "resolved",
      "urgency": "medium**"
    }
  },
  "scope": "remote"
}