{
  "debianbug": 852742,
  "description": "python-oslo-middleware before versions 3.8.1, 3.19.1, 3.23.1 is vulnerable to an information disclosure. Software using the CatchError class could include sensitive values in a traceback's error message. System users could exploit this flaw to obtain sensitive information from OpenStack component error logs (for example, keystone tokens).",
  "releases": {
    "bullseye": {
      "fixed_version": "3.19.0-3",
      "repositories": {
        "bullseye": "3.37.1-2"
      },
      "status": "resolved",
      "urgency": "low**"
    },
    "buster": {
      "fixed_version": "3.19.0-3",
      "repositories": {
        "buster": "3.36.0-2"
      },
      "status": "resolved",
      "urgency": "low**"
    },
    "sid": {
      "fixed_version": "3.19.0-3",
      "repositories": {
        "sid": "3.37.1-2"
      },
      "status": "resolved",
      "urgency": "low**"
    },
    "stretch": {
      "fixed_version": "3.19.0-3",
      "repositories": {
        "stretch": "3.19.0-3"
      },
      "status": "resolved",
      "urgency": "low**"
    }
  },
  "scope": "local"
}